# Building blocks.
# A simple, yet powerful, framework for building a python script.
from rich.console import Console
from utils.console import print_markdown, print_step, print_substep
from utils.clear import clear

console = Console()

clear()

print_markdown("""
# Welcome to pyBlocks! 
""")

def add_print():
    print_step("Add print")
    console.print("What do you want to print?")
    whatToPrint = input(" > ")
    with open("result.py", "a") as f:
        f.write(f"""
print("{whatToPrint}")        
    """)


def add_input():
    print_step("Add input")
    console.print("What do you want to ask as input?")
    whatToInput = input(" > ")
    console.print("Do you want to store the input in a variable?")
    saveToVar = input(" > ")
    if saveToVar == "yes":
        console.print("What do you want to name the variable?")
        varName = input(" > ")
        with open("result.py", "a") as f:
            f.write(f"""
{varName} = input("{whatToInput}")
""")
    else:
        with open("result.py", "a") as f:
            f.write(f"""
input("{whatToInput}")
""")


def add_variable():
    print_step("Add variable")
    console.print("What do you want to name the variable?")
    varName = input(" > ")
    console.print("Do you want to store something in the variable?")
    checkIfWantToStore = input(" > ")
    if checkIfWantToStore == "yes":
        console.print("What do you want to store in the variable? (if you want to store a string, use quotes)")
        varValue = input(" > ")
        with open("result.py", "a") as f:
            f.write(f"""
{varName} = {varValue}
""")
    else:
        with open("result.py", "a") as f:
            f.write(f"""
{varName} = "VARIABLE GENERATED BY BUILDING BLOCKS"
""")


def add_if():
    print_step("Add if")
    console.print("What variable do you want to check?")
    varName = input(" > ")
    console.print("How do you want to check the variable? (eg ==, !=, >, <, >=, <=)")
    checkType = input(" > ")
    console.print("What do you want to check the variable against? (eg a string, a number)")
    checkValue = input(" > ")
    console.print("What shloud happen if the condition is true?")
    ifTrue = input(" > ")
    console.print("What shloud happen if the condition is false?")
    ifFalse = input(" > ")
    with open("result.py", "a") as f:
        f.write(f"""
if {varName} {checkType} {checkValue}:
    {ifTrue}
else:
    {ifFalse}
""")

# Add list

def main():
    while True:
        try:
            console.print("What do you want to do?")
            answer = input(" > ")
        except KeyboardInterrupt:
            console.print("Goodbye!")
            break
        if answer == "add print":
            add_print()
        elif answer == "add input":
            add_input()
        elif answer == "add variable":
            add_variable()
        elif answer == "add if":
            add_if()
        elif answer == "done":
            break


if __name__ == '__main__':
    main()
